// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOM-3OfIhHRSxpwkC0SIevqe_yIM8Jd2s',
    appId: '1:527935952171:web:05efc2b1bc3abf1e64616e',
    messagingSenderId: '527935952171',
    projectId: 'heritrace',
    authDomain: 'heritrace.firebaseapp.com',
    storageBucket: 'heritrace.firebasestorage.app',
    measurementId: 'G-PX9DNG14GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGpc4dCQfS1nyLnVv9Wk0UmPJ0SDqmefs',
    appId: '1:527935952171:android:c0b71e354ffcb03964616e',
    messagingSenderId: '527935952171',
    projectId: 'heritrace',
    storageBucket: 'heritrace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbssSf0B5VaaQ_3_pUAgWA_Hpy2_10Wzo',
    appId: '1:527935952171:ios:54445b71d9948f7564616e',
    messagingSenderId: '527935952171',
    projectId: 'heritrace',
    storageBucket: 'heritrace.firebasestorage.app',
    iosBundleId: 'com.example.heritrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbssSf0B5VaaQ_3_pUAgWA_Hpy2_10Wzo',
    appId: '1:527935952171:ios:54445b71d9948f7564616e',
    messagingSenderId: '527935952171',
    projectId: 'heritrace',
    storageBucket: 'heritrace.firebasestorage.app',
    iosBundleId: 'com.example.heritrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOM-3OfIhHRSxpwkC0SIevqe_yIM8Jd2s',
    appId: '1:527935952171:web:e04d2cddb6054b3964616e',
    messagingSenderId: '527935952171',
    projectId: 'heritrace',
    authDomain: 'heritrace.firebaseapp.com',
    storageBucket: 'heritrace.firebasestorage.app',
    measurementId: 'G-DTDTF9TG39',
  );
}
